name: kabam
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pandas=1.3.5
  - numpy=1.21.2
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - pyarrow=6.0.1
  - ipykernel=6.6.0
  - scipy=1.7.3
  - scikit-learn=1.0.1
  - xgboost=1.5.0
  - sqlalchemy=1.4.27
